/**
 * Class TriggerFactory
 *
 * Used to instantiate and execute Trigger Handlers associated with sObjects.
 */
public without sharing class TriggerFactory{
    public TriggerFactory(){
        
    }
    //not using trigger factory
    /**
     * private static method to get the appropriate handler for the class type
     * No modifications requried in this method
     *
     * Arguments: Type - Class Type, which implements ITrigger interface
     *
     * Returns: ITrigger - A trigger handler if one exists or null
     */
    
}